# Application configuration for NNIPA Tenant Management Service
spring:
  application:
    name: tenant-management-service

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  # Database Configuration
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/tenant_db_dev}
    username: ${DB_USERNAME:tenant_user}
    password: ${DB_PASSWORD:tenant_pass}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000

  # Jackson Configuration
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
      indent-output: false
    deserialization:
      fail-on-unknown-properties: false
    time-zone: UTC
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 25
          batch_versioned_data: true
        order_inserts: true
        order_updates: true

  # Flyway Configuration
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  # Redis Cache Configuration
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

  # Cache Configuration
  cache:
    type: redis
    redis:
      time-to-live: 600000
      cache-null-values: false
      use-key-prefix: true
      key-prefix: "nnipa:tenant:"

# Service Integration Configuration
services:
  # Authentication Service
  auth:
    url: ${AUTH_SERVICE_URL:http://auth-service:8080}
    timeout: 5000
    retry:
      max-attempts: 3
      backoff: 1000

  # Authorization Service
  authorization:
    url: ${AUTHZ_SERVICE_URL:http://authz-service:8080}
    timeout: 5000
    retry:
      max-attempts: 3
      backoff: 1000

  # Notification Service
  notification:
    url: ${NOTIFICATION_SERVICE_URL:http://notification-service:8080}
    timeout: 3000
    retry:
      max-attempts: 2
      backoff: 500
    async: true

  # API Gateway (for rate limiting info)
  api-gateway:
    url: ${API_GATEWAY_URL:http://api-gateway:8080}
    internal-url: ${API_GATEWAY_INTERNAL_URL:http://api-gateway-internal:8081}

# Circuit Breaker Configuration
resilience4j:
  circuitbreaker:
    instances:
      auth-service:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true

      authz-service:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 3

      notification-service:
        sliding-window-size: 5
        failure-rate-threshold: 70
        wait-duration-in-open-state: 20s
        permitted-number-of-calls-in-half-open-state: 2

  retry:
    instances:
      auth-service:
        max-attempts: 3
        wait-duration: 1s

      notification-service:
        max-attempts: 2
        wait-duration: 500ms

# Management & Monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,caches
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    db:
      enabled: true
    redis:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
      environment: ${spring.profiles.active}
  prometheus:
    metrics:
      export:
        enabled: true

# Logging Configuration
logging:
  level:
    com.nnipa.tenant: ${LOG_LEVEL:INFO}
    org.springframework.web: ${SPRING_LOG_LEVEL:INFO}
    org.hibernate: ${HIBERNATE_LOG_LEVEL:WARN}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Server Configuration
server:
  port: ${SERVER_PORT:8082}
  servlet:
    context-path: /tenant-management
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
  error:
    include-message: always
    include-binding-errors: always

# OpenAPI/Swagger Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha

# Application-specific Configuration
app:
  tenant:
    # Default tenant isolation strategy for new tenants
    default-isolation-strategy: SHARED_SCHEMA_ROW_LEVEL

    # Provisioning Configuration
    provisioning:
      auto-activate: false  # Auto-activate after provisioning
      async-provisioning: true  # Use async for long-running operations
      retry-max-attempts: 3
      retry-delay-seconds: 60

    # Database provisioning settings
    admin-datasource:
      url: ${ADMIN_DB_URL:jdbc:postgresql://localhost:5001/postgres}
      username: ${ADMIN_DB_USERNAME:${DB_USERNAME:postgres}}
      password: ${ADMIN_DB_PASSWORD:${DB_PASSWORD:postgres}}
      driver-class-name: org.postgresql.Driver

    # Schema provisioning settings
    schema:
      prefix: tenant_
      template: tenant_template

    # Subscription defaults
    subscription:
      default-trial-days: 14
      auto-renew: true
      grace-period-days: 7

    # Feature flag defaults
    features:
      auto-enable-basic: true
      trial-features:
        - ADVANCED_ANALYTICS
        - DATA_EXPORT
        - CUSTOM_DASHBOARDS

    # Usage tracking
    usage:
      tracking-interval: HOURLY
      aggregation-interval: DAILY
      retention-days: 90

    # Organization defaults by type
    organization-defaults:
      government:
        compliance-frameworks:
          - FISMA
          - FEDRAMP
        data-retention-days: 2555  # 7 years
      healthcare:
        compliance-frameworks:
          - HIPAA
        data-retention-days: 2190  # 6 years
      financial:
        compliance-frameworks:
          - SOX
          - PCI_DSS
        data-retention-days: 2555  # 7 years
      academic:
        compliance-frameworks:
          - FERPA
        data-retention-days: 1095  # 3 years
      default:
        compliance-frameworks:
          - GDPR
        data-retention-days: 365   # 1 year

  # Async processing configuration
  async:
    core-pool-size: 4
    max-pool-size: 10
    queue-capacity: 100
    thread-name-prefix: nnipa-async-

  # Encryption for database passwords
  encryption:
    key: ${ENCRYPTION_KEY:DefaultEncryptionKey123}  # Change in production!

  # Spring async configuration
  task:
    execution:
      pool:
        core-size: 4
        max-size: 10
        queue-capacity: 100
    scheduling:
      pool:
        size: 2

  # Add logging for provisioning
  logging:
    level:
      com.nnipa.tenant.service.TenantProvisioningService: DEBUG
      com.nnipa.tenant.service.SchemaManagementService: DEBUG
      com.nnipa.tenant.service.DatabaseProvisioningService: DEBUG