# Development Environment Configuration
spring:
  # Development Database
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5000/tenant_db_dev}
    username: ${DB_USERNAME:tenant_dev}
    password: ${DB_PASSWORD:dev_password}

  # JPA Development Settings
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        generate_statistics: true

  # Redis Development
  data:
    redis:
      host: localhost
      port: 6379

  # Cache Settings for Dev
  cache:
    redis:
      time-to-live: 60000  # 1 minute for faster development testing

# Actuator - All endpoints exposed in dev
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
      show-components: always

# Server Configuration
server:
  port: 8080
  error:
    include-stacktrace: always

# Logging - More verbose in development
logging:
  level:
    root: INFO
    com.nnipa: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.cache: TRACE
    org.springframework.data.redis: DEBUG

# API Documentation - Fully enabled
springdoc:
  swagger-ui:
    enabled: true
    try-it-out-enabled: true
    filter: true
    show-extensions: true
    show-common-extensions: true

# Application Settings for Development
app:
  tenant:
    cache-ttl-minutes: 1  # Short cache for development
    trial-period-days: 90  # Longer trial for testing

  security:
    jwt-secret: dev-secret-key-not-for-production
    jwt-expiration-ms: 86400000  # 24 hours for development

  integration:
    # Local service URLs for development
    auth-service-url: http://localhost:8081
    billing-service-url: http://localhost:8082
    notification-service-url: http://localhost:8083

# Development-specific features
debug: true
trace: false